// GENERATED by scripts/dump_movedex.py from poke_env.data.GenData.from_gen(9)
// - do not hand-edit. Regenerate via .venv/bin/python scripts/dump_movedex.py.
#pragma once

#include "be/types.hpp"

namespace be {

// One move's Tier-1-relevant fields (see plans/precious-crafting-bachman.md's
// tiered mechanics scope) - everything forward_model.hpp's
// sample_damage_fraction()/resolve_turn() need to simulate a move's direct
// damage. Move EFFECTS beyond direct damage (stat boosts, hazard setup,
// status infliction, ...) are Tier 2, deferred, and not represented here.
struct MovedexEntry {
  int base_power;
  Type type;
  MoveCategory category;
  int priority;
  // Raw crit-ratio value: 0 or 1 both mean the base 1/24 rate, 2/3/4 are
  // the real gen7+ boosted-crit-stage ratios, 6 means "always crits"
  // (poke-env's willCrit marker) - see forward_model.hpp's crit_chance()
  // for the ratio -> probability table (mirrors damage.py's
  // _CRIT_CHANCE_BY_RATIO exactly).
  int crit_ratio;
  // 0-100, or -1 for "always hits" (raw dex accuracy == true).
  int accuracy;
  // 0 = not a fixed-damage move (use the base_power formula); -1 =
  // level-based (Seismic Toss, Night Shade); positive N = flat N damage
  // (Dragon Rage, Sonic Boom) - mirrors damage.py's _fixed_damage().
  int fixed_damage;
  // Equal for a fixed hit count (including the flat-3/flat-10 special
  // cases named in this script's own module docstring). A real gen-9
  // variable-multihit move's range is always exactly [2, 5].
  int min_hits;
  int max_hits;
};

// Looks up a move by its poke-env move id (e.g. "stealthrock", "uturn" -
// already hyphen/space-free, matching poke-env's own dex key format
// directly, no separate normalization needed). Returns nullptr if not
// found (should not happen for any real gen9 move reachable from a live
// battle or a PokemonSlot::moves entry).
const MovedexEntry* lookup_movedex(const char* move_id);

}  // namespace be
