// GENERATED by scripts/dump_pokedex.py from poke_env.data.GenData.from_gen(9)
// - do not hand-edit. Regenerate via .venv/bin/python scripts/dump_pokedex.py.
#pragma once

#include <cstdint>

#include "be/types.hpp"

namespace be {

inline constexpr int kNumTypes = 18;

// type_chart[defender][attacker] = damage multiplier (0, 0.25, 0.5, 1, 2, 4)
// - indexed by Type's underlying enum value (types.hpp), NOT alphabetically.
// Verified directionality against poke_env's PokemonType.damage_multiplier:
// `type_chart[type_1.name][self.name]` where type_1 is the DEFENDER's type
// and self is the calling (ATTACKING) type - so outer index = defender,
// inner index = attacker. A single-typed defender's real multiplier is
// kTypeChart[defender_type][attacker_type] alone; a dual-typed defender's
// is the PRODUCT of both of its type rows at [attacker_type].
extern const float kTypeChart[kNumTypes][kNumTypes];

struct PokedexEntry {
  StatBlock base_stats;
  Type type1;
  Type type2;  // Type::None if single-typed
};

// Looks up a species by its poke-env base_species id (lowercase - e.g.
// "bronzong", "terapagos", NOT the in-battle form-changed name like
// "terapagosterastal" - matches this project's existing base_species
// keying convention elsewhere in the Python codebase). Returns nullptr if
// not found (should not happen for any real gen9 species reachable from a
// live battle).
const PokedexEntry* lookup_pokedex(const char* base_species);

}  // namespace be
