"""Dumps poke-env's real gen-9 movedex (base power, type, category, priority,
crit ratio, accuracy, fixed-damage formula, multi-hit range) into
cpp/src/movedex_table.cpp + cpp/include/be/movedex_table.hpp - real verified
data (poke_env.data.GenData.from_gen(9)), not hand-transcribed, same practice
as scripts/dump_pokedex.py.

Field derivations were checked directly against poke-env's own Move class
properties (poke_env.battle.move.Move), not assumed from the raw dex dict
shape, since some fields (crit_ratio, accuracy) need real translation:
- crit_ratio mirrors Move.crit_ratio exactly: the raw 'critRatio' int if
  present, else 6 if the move has a 'willCrit' key (e.g. Frost Breath, Storm
  Throw - always crit), else 0 (base 1/24 rate). Checked: 'critRatio' is
  absent (None) for every willCrit move in the real gen-9 dex, and vice
  versa - the two never coexist.
- accuracy is -1 for "always hits" (raw dex value `True`, e.g. Stealth Rock,
  Swift) or the raw 0-100 int otherwise. No move has raw accuracy False or
  a value outside [1, 100] in real gen-9 data (checked directly).
- fixed_damage mirrors damage.py's _fixed_damage(): 0 = normal move (use
  the base_power formula), -1 = 'level'-based (Seismic Toss, Night Shade),
  or the flat positive value (Dragon Rage 40, Sonic Boom 20). HP-dependent
  variants (Super Fang, Final Gambit, Endeavor) have no 'damage' key at all
  in the raw dex (their real formula is a damageCallback, not a plain
  value) and fall through to fixed_damage=0 same as any other move whose
  base_power also happens to be 0 - matching damage.py's own documented
  choice to leave these unhandled rather than approximate them.
- min_hits/max_hits come from the raw 'multihit' field: absent means a
  normal 1-hit move, an int means a fixed hit count (2, 3, or 10 - Double
  Hit, Triple Kick/Axel, Population Bomb are the real gen-9 examples,
  verified directly), and a [2, 5] list is the standard variable multi-hit
  range (Bullet Seed, Pin Missile, ...) - every real gen-9 variable-multihit
  move uses exactly this range (checked: no other [lo, hi] pair appears).
  Triple Kick/Triple Axel's real mechanic (rising base power AND a separate
  accuracy check per hit) is NOT captured by a flat 3-hit count alone - a
  real, deliberate forward_model.hpp-level simplification, not a gap in
  this dump.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from poke_env.data import GenData

_TYPE_ORDER = [
    "NORMAL", "FIRE", "WATER", "ELECTRIC", "GRASS", "ICE", "FIGHTING",
    "POISON", "GROUND", "FLYING", "PSYCHIC", "BUG", "ROCK", "GHOST",
    "DRAGON", "DARK", "STEEL", "FAIRY",
]
_VALID_TYPES = set(_TYPE_ORDER)
_CATEGORY_ENUM = {
    "Physical": "MoveCategory::Physical",
    "Special": "MoveCategory::Special",
    "Status": "MoveCategory::Status",
}

_HEADER_TEMPLATE = """\
// GENERATED by scripts/dump_movedex.py from poke_env.data.GenData.from_gen(9)
// - do not hand-edit. Regenerate via .venv/bin/python scripts/dump_movedex.py.
#pragma once

#include "be/types.hpp"

namespace be {

// One move's Tier-1-relevant fields (see plans/precious-crafting-bachman.md's
// tiered mechanics scope) - everything forward_model.hpp's
// sample_damage_fraction()/resolve_turn() need to simulate a move's direct
// damage. Move EFFECTS beyond direct damage (stat boosts, hazard setup,
// status infliction, ...) are Tier 2, deferred, and not represented here.
struct MovedexEntry {
  int base_power;
  Type type;
  MoveCategory category;
  int priority;
  // Raw crit-ratio value: 0 or 1 both mean the base 1/24 rate, 2/3/4 are
  // the real gen7+ boosted-crit-stage ratios, 6 means "always crits"
  // (poke-env's willCrit marker) - see forward_model.hpp's crit_chance()
  // for the ratio -> probability table (mirrors damage.py's
  // _CRIT_CHANCE_BY_RATIO exactly).
  int crit_ratio;
  // 0-100, or -1 for "always hits" (raw dex accuracy == true).
  int accuracy;
  // 0 = not a fixed-damage move (use the base_power formula); -1 =
  // level-based (Seismic Toss, Night Shade); positive N = flat N damage
  // (Dragon Rage, Sonic Boom) - mirrors damage.py's _fixed_damage().
  int fixed_damage;
  // Equal for a fixed hit count (including the flat-3/flat-10 special
  // cases named in this script's own module docstring). A real gen-9
  // variable-multihit move's range is always exactly [2, 5].
  int min_hits;
  int max_hits;
};

// Looks up a move by its poke-env move id (e.g. "stealthrock", "uturn" -
// already hyphen/space-free, matching poke-env's own dex key format
// directly, no separate normalization needed). Returns nullptr if not
// found (should not happen for any real gen9 move reachable from a live
// battle or a PokemonSlot::moves entry).
const MovedexEntry* lookup_movedex(const char* move_id);

}  // namespace be
"""

_CPP_HEADER = """\
// GENERATED by scripts/dump_movedex.py - do not hand-edit.
#include "be/movedex_table.hpp"

#include <string>
#include <unordered_map>

namespace be {{

namespace {{
const std::unordered_map<std::string, MovedexEntry> kMovedex = {{
{movedex_entries}
}};
}}  // namespace

const MovedexEntry* lookup_movedex(const char* move_id) {{
  auto it = kMovedex.find(move_id);
  if (it == kMovedex.end()) return nullptr;
  return &it->second;
}}

}}  // namespace be
"""


def _type_enum_name(showdown_type: str) -> str:
    return "Type::" + showdown_type[0] + showdown_type[1:].lower()


def _crit_ratio(entry: dict) -> int:
    if "critRatio" in entry:
        return int(entry["critRatio"])
    if "willCrit" in entry:
        return 6
    return 0


def _accuracy(entry: dict) -> int:
    acc = entry["accuracy"]
    if acc is True:
        return -1
    return int(acc)


def _fixed_damage(entry: dict) -> int:
    dmg = entry.get("damage")
    if dmg == "level":
        return -1
    if isinstance(dmg, int) and dmg > 0:
        return dmg
    return 0


def _hit_range(entry: dict) -> tuple[int, int]:
    mh = entry.get("multihit")
    if mh is None:
        return 1, 1
    if isinstance(mh, list):
        return int(mh[0]), int(mh[1])
    return int(mh), int(mh)


def _build_movedex_entries(movedex: dict) -> str:
    lines = []
    skipped = []
    for move_id in sorted(movedex):
        entry = movedex[move_id]
        move_type = entry["type"].upper()
        # Real gen-9 data has no move outside the 18-type set (checked
        # directly - unlike dump_pokedex.py's pokedex, there's no
        # "missingno"-style placeholder move) - this filter exists so a
        # future dex addition with a new type can't silently corrupt the
        # table instead of failing loudly here.
        if move_type not in _VALID_TYPES:
            skipped.append(move_id)
            continue
        base_power = int(entry["basePower"])
        type_enum = _type_enum_name(move_type)
        category = _CATEGORY_ENUM[entry["category"]]
        priority = int(entry["priority"])
        crit_ratio = _crit_ratio(entry)
        accuracy = _accuracy(entry)
        fixed_damage = _fixed_damage(entry)
        min_hits, max_hits = _hit_range(entry)
        lines.append(
            f'    {{"{move_id}", {{{base_power}, {type_enum}, {category}, '
            f'{priority}, {crit_ratio}, {accuracy}, {fixed_damage}, '
            f'{min_hits}, {max_hits}}}}},'
        )
    if skipped:
        print(f"Skipped {len(skipped)} entries with an out-of-scope type: {skipped}")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", type=Path, default=Path("cpp"))
    args = parser.parse_args()

    gen_data = GenData.from_gen(9)
    movedex = gen_data.moves

    header = _HEADER_TEMPLATE
    cpp = _CPP_HEADER.format(movedex_entries=_build_movedex_entries(movedex))

    header_path = args.out_dir / "include" / "be" / "movedex_table.hpp"
    cpp_path = args.out_dir / "src" / "movedex_table.cpp"
    header_path.write_text(header)
    cpp_path.write_text(cpp)
    print(f"Wrote {header_path} and {cpp_path} ({len(movedex)} moves)")


if __name__ == "__main__":
    main()
