"""Dumps poke-env's real gen-9 pokedex (base stats, types) and 18x18 type
chart into cpp/src/pokedex_table.cpp + cpp/include/be/pokedex_table.hpp -
real verified data (poke_env.data.GenData.from_gen(9)), not hand-transcribed.
Regenerate via this script if it ever goes stale; don't hand-edit the
generated files.

Keyed by base_species (lowercased), matching this project's existing
identity-stability convention (see encoding.py/dataset.py's own base_species
keying, added after the Terapagos/Minior form-change bug documented in
CLAUDE.md). Verified against real data before trusting it (same practice as
every other milestone here): poke-env's own `baseSpecies` field is
inconsistently cased across entries (e.g. 'terapagosterastal' points to
baseSpecies='Terapagos', capitalized, while 'terapagos' itself points to
baseSpecies='terapagos', lowercase) - entries are grouped by
base_species.lower(), and among entries sharing a group, the one whose own
dict key already equals that lowered base_species is preferred (the true
base form), falling back to the alphabetically-first key otherwise for
determinism. 1,599 raw pokedex entries collapse to 1,356 distinct species
this way (checked directly, not assumed).
"""

from __future__ import annotations

import argparse
from pathlib import Path

from poke_env.data import GenData

_TYPE_ORDER = [
    "NORMAL", "FIRE", "WATER", "ELECTRIC", "GRASS", "ICE", "FIGHTING",
    "POISON", "GROUND", "FLYING", "PSYCHIC", "BUG", "ROCK", "GHOST",
    "DRAGON", "DARK", "STEEL", "FAIRY",
]
_STAT_ORDER = ["hp", "atk", "def", "spa", "spd", "spe"]

_HEADER_TEMPLATE = """\
// GENERATED by scripts/dump_pokedex.py from poke_env.data.GenData.from_gen(9)
// - do not hand-edit. Regenerate via .venv/bin/python scripts/dump_pokedex.py.
#pragma once

#include <cstdint>

#include "be/types.hpp"

namespace be {{

inline constexpr int kNumTypes = {n_types};

// type_chart[defender][attacker] = damage multiplier (0, 0.25, 0.5, 1, 2, 4)
// - indexed by Type's underlying enum value (types.hpp), NOT alphabetically.
// Verified directionality against poke_env's PokemonType.damage_multiplier:
// `type_chart[type_1.name][self.name]` where type_1 is the DEFENDER's type
// and self is the calling (ATTACKING) type - so outer index = defender,
// inner index = attacker. A single-typed defender's real multiplier is
// kTypeChart[defender_type][attacker_type] alone; a dual-typed defender's
// is the PRODUCT of both of its type rows at [attacker_type].
extern const float kTypeChart[kNumTypes][kNumTypes];

struct PokedexEntry {{
  StatBlock base_stats;
  Type type1;
  Type type2;  // Type::None if single-typed
}};

// Looks up a species by its poke-env base_species id (lowercase - e.g.
// "bronzong", "terapagos", NOT the in-battle form-changed name like
// "terapagosterastal" - matches this project's existing base_species
// keying convention elsewhere in the Python codebase). Returns nullptr if
// not found (should not happen for any real gen9 species reachable from a
// live battle).
const PokedexEntry* lookup_pokedex(const char* base_species);

}}  // namespace be
"""

_CPP_HEADER = """\
// GENERATED by scripts/dump_pokedex.py - do not hand-edit.
#include "be/pokedex_table.hpp"

#include <unordered_map>
#include <string>

namespace be {{

const float kTypeChart[kNumTypes][kNumTypes] = {{
{type_chart_rows}
}};

namespace {{
const std::unordered_map<std::string, PokedexEntry> kPokedex = {{
{pokedex_entries}
}};
}}  // namespace

const PokedexEntry* lookup_pokedex(const char* base_species) {{
  auto it = kPokedex.find(base_species);
  if (it == kPokedex.end()) return nullptr;
  return &it->second;
}}

}}  // namespace be
"""


def _type_enum_name(showdown_type: str) -> str:
    return "Type::" + showdown_type[0] + showdown_type[1:].lower()


def _build_type_chart_rows(type_chart: dict) -> str:
    rows = []
    for defender in _TYPE_ORDER:
        values = [str(float(type_chart[defender][attacker])) + "f" for attacker in _TYPE_ORDER]
        rows.append("    {" + ", ".join(values) + "},")
    return "\n".join(rows)


def _dedupe_by_base_species(pokedex: dict) -> dict:
    groups: dict[str, list[str]] = {}
    for key, entry in pokedex.items():
        base = entry.get("baseSpecies", key).lower()
        groups.setdefault(base, []).append(key)

    chosen = {}
    for base, keys in groups.items():
        if base in keys:
            chosen[base] = pokedex[base]
        else:
            chosen[base] = pokedex[sorted(keys)[0]]
    return chosen


_VALID_TYPES = {t.upper() for t in _TYPE_ORDER}


def _build_pokedex_entries(pokedex: dict) -> str:
    lines = []
    skipped = []
    for base_species in sorted(pokedex):
        entry = pokedex[base_species]
        types = entry["types"]
        # Real gen-9 data has exactly one non-competitive placeholder entry
        # ("missingno", a Showdown glitch-mon stub with a scrapped gen-1
        # "Bird" type) that isn't reachable in any real battle/format -
        # verified directly (1 offender out of 1123 species) before adding
        # this filter, not assumed. Skips anything with a type outside the
        # real 18-type set, not just that one name, in case the dex ever
        # grows another one.
        if any(t.upper() not in _VALID_TYPES for t in types):
            skipped.append(base_species)
            continue
        stats = entry["baseStats"]
        type1 = _type_enum_name(types[0].upper())
        type2 = _type_enum_name(types[1].upper()) if len(types) > 1 else "Type::None"
        stat_block = ", ".join(str(stats[s]) for s in _STAT_ORDER)
        lines.append(
            f'    {{"{base_species}", {{{{{stat_block}}}, {type1}, {type2}}}}},'
        )
    if skipped:
        print(f"Skipped {len(skipped)} non-competitive entries: {skipped}")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", type=Path, default=Path("cpp"))
    args = parser.parse_args()

    gen_data = GenData.from_gen(9)
    type_chart = gen_data.type_chart
    pokedex = _dedupe_by_base_species(gen_data.pokedex)

    header = _HEADER_TEMPLATE.format(n_types=len(_TYPE_ORDER))
    cpp = _CPP_HEADER.format(
        type_chart_rows=_build_type_chart_rows(type_chart),
        pokedex_entries=_build_pokedex_entries(pokedex),
    )

    header_path = args.out_dir / "include" / "be" / "pokedex_table.hpp"
    cpp_path = args.out_dir / "src" / "pokedex_table.cpp"
    header_path.write_text(header)
    cpp_path.write_text(cpp)
    print(f"Wrote {header_path} and {cpp_path} ({len(pokedex)} species, {len(_TYPE_ORDER)} types)")


if __name__ == "__main__":
    main()
